# Generated by Django 4.0.6 on 2022-09-03 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sportsbook', '0002_update_bet_wager'),
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.CharField(max_length=32)),
            ],
        ),
        migrations.RemoveField(
            model_name='bet',
            name='spread_bet',
        ),
        migrations.AddField(
            model_name='bet',
            name='market',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='market_bet', to='sportsbook.market'),
        ),
    ]
