# Generated by Django 4.0.6 on 2022-09-03 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsbook', '0003_market_remove_bet_spread_bet_bet_market'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.FloatField(default=500),
        ),
    ]
