# Generated by Django 4.0.6 on 2022-09-03 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsbook', '0004_user_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='pending',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bet',
            name='won',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
