# Generated by Django 4.0.6 on 2022-09-04 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsbook', '0008_game_away_ml_game_home_ml'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='commence_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
