# Generated by Django 4.0.6 on 2022-09-04 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsbook', '0009_game_commence_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='api_id',
            field=models.CharField(default='no-id', max_length=128),
        ),
        migrations.AddField(
            model_name='game',
            name='away_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='home_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
