# Generated by Django 4.0.6 on 2022-09-05 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsbook', '0010_game_api_id_game_away_score_game_completed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bet',
            name='pending',
        ),
        migrations.AddField(
            model_name='bet',
            name='profit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bet',
            name='won',
            field=models.CharField(default='Pending', max_length=8),
        ),
    ]
