# Generated by Django 4.0.6 on 2022-09-09 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsbook', '0012_rename_won_bet_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pending',
            field=models.FloatField(default=0),
        ),
    ]
